name: Setup Node with Cache
description: |
  This action sets up Node.js, caches npm dependencies, and installs them.
  It is designed to be reusable in multiple workflows.

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '23.7.0'

runs:
  using: composite
  steps:
    - name: 🔧 Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: 📦 Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 📦 Install dependencies
      run: npm ci
      shell: bash
